language: python
dist: xenial
python:
- '3.8'
before-install:
- wget -N https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
addons:
  chrome: stable
before_script:
- pip install -r requirements.txt
- google-chrome-stable --no-sandbox --disable-dev-shm-usage --headless --start-maximized
  --disable-gpu --remote-debugging-port=9222 http://localhost &
env:
  global:
  - DJANGO_SETTINGS_MODULE=healthieralt.settings.travis
  - secure: eDtVI6HwrLpN35aq/scCRT3Pjiz9nQSvquyy52LdGwih/MQqufbeEbNE4YMVh9Cm16GqurEn1H31Pbu51NXEZpGV7MDEaMs2hVRP1AK1WV8csxrXODScQzB8anR2XQxGgk5dWqh0xu2XZOvWL+QJnoi7KSlgaKa8qTABvkZtMFB2TYXXpSB0tKI+ISNmoDDLicwxhZK2IFSrxvfBJ7VMsPCUh3Z7hJbxd6mONZeUoyOISGEcL+1FC3n0y1/ce/xeekTaLjKEvJehr64JrFnhs2/B63rPPlzPFn8OoGeHBgDpwyrCIevyqR2t2LiftPcC0CO90MQqMkfUHYOidW6/m3+CAnGxQATC8nKcY1ODDQZ5tTDyDypO9ovIr5b1fuWA2WHF2mlNxnMh5Y7vzPZmMZwRpVMoDcUsFwOjfSEzZgMewdZj6ChDP4oqhZ75VhL2ywaNqbbJSoBki0qtiSouoNLfSFm2a2UtjLTHw938mNg+IafRPKUjsfhYPV2n9HZJYpBeA7IJQREXvbSWWd1H0iX1zHXXoEqNNvqs4s3+a/B/sIjFCXNYOTPS2UuvrqKKRLNYWKF9b4UPcQalAHssnygpKbDa7sGnutjS2iQahwMzdRZJHI4+L9emedqFFUnL0LXpwA0V17OEzc7GU2ur/Yh7crOLhh6NG5mQEjO6bKo=
  - secure: Bky8vr47VXEKqCT5NafaER0JPE0i4xI3EqhtWLpBoZZ9vQcdrTX3cJqMhyuBToz6SO1Wxpw6YfOOK5Qftv6URvt2fK87P4gvcz2xyW/IHGf+RXgRDDcEiMyN7P3hnz5lAN3S2tchHu4C3aY0ROtzQczKNQseze9mXgNFsQN0uMeIOxoZvjSlksKuuYZkS7J57jRpC5s5HNrBWIRm3QWAj5V5X81r5oYOeoQs0yfPqo1rr8MvgnTeOko/r2MYVZEy7X52dJ3hfUiCRIMV3v338fPkCffcODpmm9+6eEdUWdqbRoHIXT/Jo+pFeqyA07lDv0KarYYHVSiEtDsAMOpslbIKRdc5cceTptHkxKAEnssCXpqy5jePAcmJwiY773hUi1ri8XpZVUV6pyocO1PwpYP8ERcMY7v80XuGax1RrB20Drii9ZSBEudpEx512CmJT3nQyyfAR0v/w3zLXb3YrPhCCzlgmG5Z0Ka2MxImP+jm8t331V2+h11C2dIdLDlDPseV/H/8KCVn1Jg+SuI1tMHufXKGfE7DgkftGqmVRD7/s4qc1SggyfxvW8DhFLjHGCLoTarDHQ9Y1rM3hXI2YARajR3knqEZgW5IZLkGZDzmncGExEaggNkKwWqruH6ZW1hcrSQx7UF2jLXopuRwLVuSgAqA9Rm7dMADbncR5n8=
  - secure: IpLxAQ9Qwtc19lwFMOqk0ZrXOvuHp7CxN5zGAF9vWfe/LQZtScCrZWuqJ2PyMGJCAfLTyqLrOEL9v32J7h4cV+KlrWg/Ra94Lh4MkA43zgPNfBsfR4FZsFL0Cr84LtqDugGGX+5JAr+0uYfbCcU1wNpDbOFQ685uQRVoYvZVuXEicmp/U2fMqxSsf2E6mjQsELgQrb1XN9njnYAlAhALUjZUvneMc36tBTmE2cZMcbcWi3+WTfI6Y2w1lf4RiFbiCRLp1WwWkzkpmJfxUdjQuXSFQ4Tkcq8nPb9N2c4TT5eC3bp9w91wOFpXkKqB7/0Fec5fAv/sIKD3OhEt9QZCFvqeXt4n1zeFtYzMAQOvKGINv1n7UEKOT5PLaSyBfo11sxwikpjAObEOg6BimbW2WEEB7rpoeYfQEhxZWWwycSzU+R6l1KEAm0sWWx6F61KP/1SFx9oF1ZjsylEKYToIIe6edkefYDPe8X7Axw+kZFIUDOznUT0Msroe8b9t/YoAKQGkjoxkp9J09rv3cUFOJBH6BNRcpuXGM1KaRL32gfbonfkilL4QugInMbVR/z2+e24/hyttPD1W1LRRFWau7fXkHqsJOW4K3ruKerDDj0MYH6A31T6NdqEmuYoktm7Exi7/1J6RJUtQhPrC+gkIQoZFvK2K4XZjuT/EGMokjdk=
  - secure: d4+ta90+Prq/i5TyHkw4nFn7hJLIP0wP51z7TMR4fwcwh8L9V0S+Qd1xS0czqH7Vju1uOQ+Si3ruobYIEcje4h8Fbf1MDE+MaJfARYi1k5OmNqcteBAomMu/Ml0QH7iuO6yqLpM7VdDpDE4Bm8NNj9nxmDZSGFUK+o5A/YYYUvGSRbas4zd8Rozz8SXrpCZG0ZpuVWPAbLPPkl7TkpFGMqW5FEETyRzK9ZfBYZc74RRPLrNS0/iICXyeHYuWl2ebUA0XS367gcrnYbJ5ifk+AofARu+aDYbqc3wylHRaaHP82diL3rBcLrhtMjpdfItOcLOlTZp2o2RXKFUAf4Bt/iC3z02RjQHptAIa0BY5gPCAtAdEIvbbWLsrFSTJ/f1EpAUvWdVBQOdMQnLSoTcyYqQLjMs/Iw2ofS3LKE4EzpfZN9HKPQKR13A2PphWkzJumlI1op0TOW/CbadOMy45U8U4Ed7U8QGOu2pmkXp+u2p11Ducfa29PfbCagOs8wvCxI4rXxaDKkQRTY1ZLfgUMdYJZZR2woOGjnOq5hiTBCA8NGc3Y4/rLDGayvVRUz9cSse5tV1RQn5NAksI6D7B087Fr3UKqrICDuGLc9Izf3dPjxPUu/S0z7j318gl+1ukIwLtsDdBDhqS8PfFEYdwBAdg4YxAGJFbYOJWrm6FODU=
  - USER_LOGIN="Pierre"
  - secure: X6eUD7uDA2A9yohS5Ks/dCaFs36n8kaz6NloCW9PMMw8LbrcRo1UnbXiagdS48ycM0Mup1o2mk6P2Rx9eU7ALhhyThipvLrOKTtWuTm7cvWmq+zMjfXi7LC8wHMGlLnGx1DbIn/+xphPcfEhIzESWNyQ5DS2ptsIeUd9kGrPpaysLqONn5hk6lJHVFRtc9XJRVV7wvs/GDejdvY1Wukift7EZI8GBSkp7aBYGswO0O2C0pXcUfzHLLOJYPYcCWB7NW5taCGeleUR6PydkPwauwZ5SFR4Dt7FCM5e1cRPGvM+sQt8JTMOjOsB41C0F96e+l3PJFRRN2U0FvbSxT7e4VI86vg0u19zWKW9y6Ymy8bf8GygE5WHad4u81snpyBxTmetzcq9bu+Lmx/5XhO97mADRJ4fkqc6gCMnLmP1G3PQ0j5y7Xu29eSz16UAG+pSvjCKxHtX8rAMNaB7OgirH3CKElwo1ngs/0NwAUpslqcSFH93Fi1zh1BOT2uCXe2Hm9dxffr06aOFAFrnPDDEd8SQ8Z5cF4RBzlpGYj4lTCAE/DX2ayu8hRQLcmyL4tjahUD7ndNFjnOB9ouY74Wu2qodd0eZaGUOuQgDnZNRxzVz5QU+BRsRwAAinU3JVbc+DxMOdo8U5GIpOidbcHdonnIxMTO8M7ZIUa9aBivEGRE=
  - ADMIN_USER_LOGIN="admin"
  - secure: EVY3jIzsM0xGjOqSgBjpTNBo/bfUeMMWfcvvFgbVWOWz2desXasz/f0orTLgW1KV7ywHrkPNeDPHydvyZ8bACguG3Gze9h7qyDh0JZ/LW4asMEFYYW0WUt57J6Yw39noUgKdChtwIGAjDEVxCyVhZEnPJvx2wIE551ycPEuhi8YTwY0tFH59L3zdIZ6p4wJKU7z0umwuUJtKRhMPKVG/WHGzzKqFFgTv2C13IQuIceWUmzqAUis1/6fbVOfC+mm0vMZL6vL+ptvGW5ST9cvQlb8MZYVHceqaUR/SXKD4nVrMtA1/Ca2t1GBmNj8bJrux1xnqQL2poDGqsBTJm471XmG/9J3hByKa/uC/OZg6BdFFFX4ZTHKPbMENixaA+JomHr8wE80H+SEQnqwf4hiCIHVlbIHdJoYx5w5A66Ut0SVnULknvz0te7OUTEWE1kp+iTNdzKSTJmURQ3O1zYKQ1tAE4q5VvoPlhWLmk7RMrNE2eQgUrTZnK+707OfQdI3XygUFk+Wmcq/LQlKGx24nxGl9SndHH7zlro/wqvuu+Z7GFXbPCts4hjVoPwdP1JqzQoWlYIg8c3fkDi0Q9wE+6M6cpC+eq9NyvtiBUYlpeFarwvjwc1lcFV7VzXB5F7VOIYlOHQQLQM7xdmPWlcLz6M/D3Yc88KXlE5yARzgRLK8=
  - SIGNUP_USERNAME="Jeandu75"
  - SIGNUP_PWD="pwdpastressecure42"
  - SIGNUP_EMAIL="Jeandu75@wanadoo.fr"
  - SIGNUP_FIRSTNAME="Jean"
  - DOG_NAME="test_dog"
  - DOG_AGE=6
  - DOG_RACE=test_race
  - DOG_NAME="test_dog"
  - DOG_AGE=6
  - DOG_RACE=test_race
services:
- postgresql
- xvfb
script:
- ".OChenil/manage.py test"
