# Generated by Django 3.2.6 on 2021-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_age',
            field=models.IntegerField(),
        ),
    ]
