# Generated by Django 3.2.6 on 2021-08-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='allowed_size',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='dog_size',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administration.size'),
        ),
        migrations.AddField(
            model_name='box',
            name='box_size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administration.size'),
        ),
        migrations.AddField(
            model_name='dog',
            name='dogsize',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administration.size'),
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.box')),
            ],
        ),
    ]
